package uk.gov.gds.ier.validation.constants

import scala.collection.immutable.HashMap

object NationalityConstants {

  def numberMaxOfOtherCountries = 3

  type Franchise = String
  object Franchise {
    def apply(str:String) = {
      require(
        str == fullValue ||
        str == europeanValue ||
        str == commonwealthValue ||
        str == britishTerritoriesValue ||
        str == crownDependenciesValue
      )
      str
    }
    private final val fullValue = "Full"
    private final val europeanValue = "EU"
    private final val commonwealthValue = "Commonwealth"
    private final val britishTerritoriesValue = "British Territories"
    private final val crownDependenciesValue = "British Crown Dependencies"

    final val full = Franchise(fullValue)
    final val european = Franchise(europeanValue)
    final val commonwealth = Franchise(commonwealthValue)
    final val britishTerritories = Franchise(britishTerritoriesValue)
    final val crownDependencies = Franchise(crownDependenciesValue)
  }

  case class ISOCountry(isoCode:String, displayName: String, franchise: Franchise*)

  lazy val countryNameToCodes = HashMap(
    "afghanistan" -> ISOCountry("AF", displayName = "Afghanistan"),
    "albania" -> ISOCountry("AL", displayName = "Albania"),
    "algeria" -> ISOCountry("DZ", displayName = "Algeria"),
    "american samoa" -> ISOCountry("AS", displayName = "American Samoa"),
    "andorra" -> ISOCountry("AD", displayName = "Andorra"),
    "angola" -> ISOCountry("AO", displayName = "Angola"),
    "anguilla" -> ISOCountry("AI", displayName = "Anguilla", Franchise.britishTerritories),
    "antigua and barbuda" -> ISOCountry("AG", displayName = "Antigua and Barbuda", Franchise.commonwealth),
    "argentina" -> ISOCountry("AR", displayName = "Argentina"),
    "armenia" -> ISOCountry("AM", displayName = "Armenia"),
    "aruba" -> ISOCountry("AW", displayName = "Aruba"),
    "australia" -> ISOCountry("AU", displayName = "Australia", Franchise.commonwealth),
    "austria" -> ISOCountry("AT", displayName = "Austria", Franchise.european),
    "azerbaijan" -> ISOCountry("AZ", displayName = "Azerbaijan"),
    "bahamas" -> ISOCountry("BS", displayName = "Bahamas", Franchise.commonwealth),
    "bahrain" -> ISOCountry("BH", displayName = "Bahrain"),
    "bangladesh" -> ISOCountry("BD", displayName = "Bangladesh", Franchise.commonwealth),
    "barbados" -> ISOCountry("BB", displayName = "Barbados", Franchise.commonwealth),
    "belarus" -> ISOCountry("BY", displayName = "Belarus"),
    "belgium" -> ISOCountry("BE", displayName = "Belgium", Franchise.european),
    "belize" -> ISOCountry("BZ", displayName = "Belize", Franchise.commonwealth),
    "benin" -> ISOCountry("BJ", displayName = "Benin"),
    "bermuda" -> ISOCountry("bm", displayName = "Bermuda", Franchise.britishTerritories),
    "bhutan" -> ISOCountry("BT", displayName = "Bhutan"),
    "bolivia" -> ISOCountry("BO", displayName = "Bolivia"),
    "bonaire/st eustatius/saba" -> ISOCountry("BQ", displayName = "Bonaire/St Eustatius/Saba"),
    "bosnia and herzegovina" -> ISOCountry("BA", displayName = "Bosnia and Herzegovina" ),
    "botswana" -> ISOCountry("BW", displayName = "Botswana", Franchise.commonwealth),
    "brazil" -> ISOCountry("BR", displayName = "Brazil"),
    "british indian ocean territory" -> ISOCountry("IO", displayName = "British Indian Ocean Territory", Franchise.britishTerritories),
    "british virgin islands" -> ISOCountry("VG", displayName = "British Virgin Islands", Franchise.britishTerritories),
    "brunei" -> ISOCountry("BN", displayName = "Brunei", Franchise.commonwealth),
    "bulgaria" -> ISOCountry("BG", displayName = "Bulgaria", Franchise.european),
    "burkina faso" -> ISOCountry("BF", displayName = "Burkina Faso"),
    "burma" -> ISOCountry("MM", displayName = "Burma"),
    "burundi" -> ISOCountry("BI", displayName = "Burundi"),
    "cambodia" -> ISOCountry("KH", displayName = "Cambodia"),
    "cameroon" -> ISOCountry("CM", displayName = "Cameroon", Franchise.commonwealth),
    "canada" -> ISOCountry("CA", displayName = "Canada", Franchise.commonwealth),
    "cape verde" -> ISOCountry("CV", displayName = "Cape Verde"),
    "cayman islands" -> ISOCountry("KY", displayName = "Cayman Islands", Franchise.britishTerritories),
    "central african republic" -> ISOCountry("CF", displayName = "Central African Republic"),
    "chad" -> ISOCountry("TD", displayName = "Chad"),
    "chile" -> ISOCountry("CL", displayName = "Chile"),
    "china" -> ISOCountry("CN", displayName = "China"),
    "colombia" -> ISOCountry("CO", displayName = "Colombia"),
    "comoros" -> ISOCountry("KM", displayName = "Comoros"),
    "congo" -> ISOCountry("CG", displayName = "Congo"),
    "costa rica" -> ISOCountry("CR", displayName = "Costa Rica"),
    "cote d’ivoire" -> ISOCountry("CI", displayName = "Cote d’Ivoire"),
    "croatia" -> ISOCountry("HR", displayName = "Croatia", Franchise.european),
    "cuba" -> ISOCountry("CU", displayName = "Cuba"),
    "curaçao" -> ISOCountry("CW", displayName = "Curaçao"),
    "cyprus" -> ISOCountry("CY", displayName = "Cyprus", Franchise.european, Franchise.commonwealth),
    "czech republic" -> ISOCountry("CZ", displayName = "Czech Republic", Franchise.european),
    "democratic republic of congo" -> ISOCountry("CD", displayName = "Democratic Republic of Congo"),
    "denmark" -> ISOCountry("DK", displayName = "Denmark", Franchise.european),
    "djibouti" -> ISOCountry("DJ", displayName = "Djibouti"),
    "dominica" -> ISOCountry("DM", displayName = "Dominica", Franchise.commonwealth),
    "dominican republic" -> ISOCountry("DO", displayName = "Dominican Republic"),
    "ecuador" -> ISOCountry("EC", displayName = "Ecuador"),
    "egypt" -> ISOCountry("EG", displayName = "Egypt"),
    "el salvador" -> ISOCountry("SV", displayName = "El Salvador"),
    "equatorial guinea" -> ISOCountry("GQ", displayName = "Equatorial Guinea"),
    "eritrea" -> ISOCountry("ER", displayName = "Eritrea"),
    "estonia" -> ISOCountry("EE", displayName = "Estonia", Franchise.european),
    "ethiopia" -> ISOCountry("ET", displayName = "Ethiopia"),
    "falkland islands" -> ISOCountry("FK", displayName = "Falkland Islands", Franchise.britishTerritories),
    "fiji" -> ISOCountry("FJ", displayName = "Fiji", Franchise.commonwealth),
    "finland" -> ISOCountry("FI", displayName = "Finland", Franchise.european),
    "france" -> ISOCountry("FR", displayName = "France", Franchise.european),
    "french guiana" -> ISOCountry("GF", displayName = "French Guiana"),
    "french polynesia" -> ISOCountry("PF", displayName = "French Polynesia"),
    "gabon" -> ISOCountry("GA", displayName = "Gabon"),
    "gambia" -> ISOCountry("GM", displayName = "Gambia", Franchise.commonwealth),
    "georgia" -> ISOCountry("GE", displayName = "Georgia"),
    "germany" -> ISOCountry("DE", displayName = "Germany", Franchise.european),
    "ghana" -> ISOCountry("GH", displayName = "Ghana", Franchise.commonwealth),
    "gibraltar" -> ISOCountry("GI", displayName = "Gibraltar", Franchise.britishTerritories),
    "greece" -> ISOCountry("GR", displayName = "Greece", Franchise.european),
    "grenada" -> ISOCountry("GD", displayName = "Grenada", Franchise.commonwealth),
    "guadeloupe" -> ISOCountry("GP", displayName = "Guadeloupe"),
    "guatemala" -> ISOCountry("GT", displayName = "Guatemala"),
    "guernsey" -> ISOCountry("GG", displayName = "Guernsey"),
    "guinea" -> ISOCountry("GN", displayName = "Guinea"),
    "guinea-bissau" -> ISOCountry("GW", displayName = "Guinea-Bissau"),
    "guyana" -> ISOCountry("GY", displayName = "Guyana", Franchise.commonwealth),
    "haiti" -> ISOCountry("HT", displayName = "Haiti"),
    "holy see" -> ISOCountry("VA", displayName = "Holy See"),
    "honduras" -> ISOCountry("HN", displayName = "Honduras"),
    "hong kong" -> ISOCountry("HK", displayName = "Hong Kong", Franchise.full),
    "hungary" -> ISOCountry("HU", displayName = "Hungary", Franchise.european),
    "iceland" -> ISOCountry("IS", displayName = "Iceland"),
    "india" -> ISOCountry("IN", displayName = "India", Franchise.commonwealth),
    "indonesia" -> ISOCountry("ID", displayName = "Indonesia"),
    "iran" -> ISOCountry("IR", displayName = "Iran"),
    "iraq" -> ISOCountry("IQ", displayName = "Iraq"),
    "ireland" -> ISOCountry("IE", displayName = "Ireland", Franchise.full, Franchise.european),
    "isle of man" -> ISOCountry("IM", displayName = "Isle of Man"),
    "israel" -> ISOCountry("IL", displayName = "Israel"),
    "italy" -> ISOCountry("IT", displayName = "Italy", Franchise.european),
    "jamaica" -> ISOCountry("JM", displayName = "Jamaica", Franchise.commonwealth),
    "japan" -> ISOCountry("JP", displayName = "Japan"),
    "jersey" -> ISOCountry("JE", displayName = "Jersey"),
    "jordan" -> ISOCountry("JO", displayName = "Jordan"),
    "kazakhstan" -> ISOCountry("KZ", displayName = "Kazakhstan"),
    "kenya" -> ISOCountry("KE", displayName = "Kenya", Franchise.commonwealth),
    "kiribati" -> ISOCountry("KI", displayName = "Kiribati", Franchise.commonwealth),
    "kosovo" -> ISOCountry("XK", displayName = "Kosovo"),
    "kuwait" -> ISOCountry("KW", displayName = "Kuwait"),
    "kyrgyzstan" -> ISOCountry("KG", displayName = "Kyrgyzstan"),
    "laos" -> ISOCountry("LA", displayName = "Laos"),
    "latvia" -> ISOCountry("LV", displayName = "Latvia", Franchise.european),
    "lebanon" -> ISOCountry("LB", displayName = "Lebanon"),
    "lesotho" -> ISOCountry("LS", displayName = "Lesotho", Franchise.commonwealth),
    "liberia" -> ISOCountry("LR", displayName = "Liberia"),
    "libya" -> ISOCountry("LY", displayName = "Libya"),
    "liechtenstein" -> ISOCountry("LI", displayName = "Liechtenstein"),
    "lithuania" -> ISOCountry("LT", displayName = "Lithuania", Franchise.european),
    "luxembourg" -> ISOCountry("LU", displayName = "Luxembourg", Franchise.european),
    "macao" -> ISOCountry("MO", displayName = "Macao"),
    "macedonia" -> ISOCountry("MK", displayName = "Macedonia"),
    "madagascar" -> ISOCountry("MG", displayName = "Madagascar"),
    "malawi" -> ISOCountry("MW", displayName = "Malawi", Franchise.commonwealth),
    "malaysia" -> ISOCountry("MY", displayName = "Malaysia", Franchise.commonwealth),
    "maldives" -> ISOCountry("MV", displayName = "Maldives", Franchise.commonwealth),
    "mali" -> ISOCountry("ML", displayName = "Mali"),
    "malta" -> ISOCountry("MT", displayName = "Malta", Franchise.european, Franchise.commonwealth),
    "marshall islands" -> ISOCountry("MH", displayName = "Marshall Islands"),
    "martinique" -> ISOCountry("MQ", displayName = "Martinique"),
    "mauritania" -> ISOCountry("MR", displayName = "Mauritania"),
    "mauritius" -> ISOCountry("MU", displayName = "Mauritius", Franchise.commonwealth),
    "mayotte" -> ISOCountry("YT", displayName = "Mayotte"),
    "mexico" -> ISOCountry("MX", displayName = "Mexico"),
    "micronesia" -> ISOCountry("FM", displayName = "Micronesia"),
    "moldova" -> ISOCountry("MD", displayName = "Moldova"),
    "monaco" -> ISOCountry("MC", displayName = "Monaco"),
    "mongolia" -> ISOCountry("MN", displayName = "Mongolia"),
    "montenegro" -> ISOCountry("ME", displayName = "Montenegro"),
    "montserrat" -> ISOCountry("MS", displayName = "Montserrat", Franchise.britishTerritories),
    "morocco" -> ISOCountry("MA", displayName = "Morocco"),
    "mozambique" -> ISOCountry("MZ", displayName = "Mozambique", Franchise.commonwealth),
    "namibia" -> ISOCountry("NA", displayName = "Namibia", Franchise.commonwealth),
    "nauru" -> ISOCountry("NR", displayName = "Nauru", Franchise.commonwealth),
    "nepal" -> ISOCountry("NP", displayName = "Nepal"),
    "netherlands" -> ISOCountry("NL", displayName = "Netherlands", Franchise.european),
    "new caledonia" -> ISOCountry("NC", displayName = "New Caledonia"),
    "new zealand" -> ISOCountry("NZ", displayName = "New Zealand", Franchise.commonwealth),
    "nicaragua" -> ISOCountry("NI", displayName = "Nicaragua"),
    "niger" -> ISOCountry("NE", displayName = "Niger"),
    "nigeria" -> ISOCountry("NG", displayName = "Nigeria", Franchise.commonwealth),
    "north korea" -> ISOCountry("KP", displayName = "North Korea"),
    "norway" -> ISOCountry("NO", displayName = "Norway"),
    "oman" -> ISOCountry("OM", displayName = "Oman"),
    "pakistan" -> ISOCountry("PK", displayName = "Pakistan", Franchise.commonwealth),
    "palau" -> ISOCountry("PW", displayName = "Palau"),
    "panama" -> ISOCountry("PA", displayName = "Panama"),
    "papua new guinea" -> ISOCountry("PG", displayName = "Papua New Guinea", Franchise.commonwealth),
    "paraguay" -> ISOCountry("PY", displayName = "Paraguay"),
    "peru" -> ISOCountry("PE", displayName = "Peru"),
    "philippines" -> ISOCountry("PH", displayName = "Philippines"),
    "pitcairn island" -> ISOCountry("PN", displayName = "Pitcairn Island", Franchise.britishTerritories),
    "poland" -> ISOCountry("PL", displayName = "Poland", Franchise.european),
    "portugal" -> ISOCountry("PT", displayName = "Portugal", Franchise.european),
    "qatar" -> ISOCountry("QA", displayName = "Qatar"),
    "réunion" -> ISOCountry("RE", displayName = "Réunion"),
    "romania" -> ISOCountry("RO", displayName = "Romania", Franchise.european),
    "russia" -> ISOCountry("RU", displayName = "Russia"),
    "rwanda" -> ISOCountry("RW", displayName = "Rwanda", Franchise.commonwealth),
    "samoa" -> ISOCountry("WS", displayName = "Samoa", Franchise.commonwealth),
    "san marino" -> ISOCountry("SM", displayName = "San Marino"),
    "são tomé and principe" -> ISOCountry("ST", displayName = "São Tomé and Principe"),
    "saudi arabia" -> ISOCountry("SA", displayName = "Saudi Arabia"),
    "senegal" -> ISOCountry("SN", displayName = "Senegal"),
    "serbia" -> ISOCountry("RS", displayName = "Serbia"),
    "seychelles" -> ISOCountry("SC", displayName = "Seychelles", Franchise.commonwealth),
    "sierra leone" -> ISOCountry("SL", displayName = "Sierra Leone", Franchise.commonwealth),
    "singapore" -> ISOCountry("SG", displayName = "Singapore", Franchise.commonwealth),
    "slovakia" -> ISOCountry("SK", displayName = "Slovakia", Franchise.european),
    "slovenia" -> ISOCountry("SI", displayName = "Slovenia", Franchise.european),
    "solomon islands" -> ISOCountry("SB", displayName = "Solomon Islands", Franchise.commonwealth),
    "somalia" -> ISOCountry("SO", displayName = "Somalia"),
    "south africa" -> ISOCountry("ZA", displayName = "South Africa", Franchise.commonwealth),
    "south georgia and the south sandwich islands" -> ISOCountry("GS", displayName = "South Georgia and the South Sandwich Islands", Franchise.britishTerritories),
    "south korea" -> ISOCountry("KR", displayName = "South Korea"),
    "south sudan" -> ISOCountry("SS", displayName = "South Sudan"),
    "spain" -> ISOCountry("ES", displayName = "Spain", Franchise.european),
    "sri lanka" -> ISOCountry("LK", displayName = "Sri Lanka", Franchise.commonwealth),
    "st helena, ascension and tristan da cunha" -> ISOCountry("SH", displayName = "St Helena, Ascension and Tristan da Cunha", Franchise.britishTerritories),
    "st kitts and nevis" -> ISOCountry("KN", displayName = "St Kitts and Nevis", Franchise.commonwealth),
    "st lucia" -> ISOCountry("LC", displayName = "St Lucia", Franchise.commonwealth),
    "st maarten" -> ISOCountry("MF", displayName = "St Maarten"),
    "st pierre & miquelon" -> ISOCountry("PM", displayName = "St Pierre & Miquelon"),
    "st vincent and the grenadines" -> ISOCountry("VC", displayName = "St Vincent and The Grenadines", Franchise.commonwealth),
    "sudan" -> ISOCountry("SD", displayName = "Sudan"),
    "suriname" -> ISOCountry("SR", displayName = "Suriname"),
    "swaziland" -> ISOCountry("SZ", displayName = "Swaziland", Franchise.commonwealth),
    "sweden" -> ISOCountry("SE", displayName = "Sweden", Franchise.european),
    "switzerland" -> ISOCountry("CH", displayName = "Switzerland"),
    "syria" -> ISOCountry("SY", displayName = "Syria"),
    "taiwan" -> ISOCountry("TW", displayName = "Taiwan"),
    "tajikistan" -> ISOCountry("TJ", displayName = "Tajikistan"),
    "tanzania" -> ISOCountry("TZ", displayName = "Tanzania", Franchise.commonwealth),
    "thailand" -> ISOCountry("TH", displayName = "Thailand"),
    "the occupied palestinian territories" -> ISOCountry("PS", displayName = "The Occupied Palestinian Territories"),
    "timor leste" -> ISOCountry("TL", displayName = "Timor Leste"),
    "togo" -> ISOCountry("TG", displayName = "Togo"),
    "tonga" -> ISOCountry("TO", displayName = "Tonga", Franchise.commonwealth),
    "trinidad and tobago" -> ISOCountry("TT", displayName = "Trinidad and Tobago", Franchise.commonwealth),
    "tunisia" -> ISOCountry("TN", displayName = "Tunisia"),
    "turkey" -> ISOCountry("TR", displayName = "Turkey"),
    "turkmenistan" -> ISOCountry("TM", displayName = "Turkmenistan"),
    "turks and caicos islands" -> ISOCountry("TC", displayName = "Turks and Caicos Islands", Franchise.britishTerritories),
    "tuvalu" -> ISOCountry("TV", displayName = "Tuvalu", Franchise.commonwealth),
    "uganda" -> ISOCountry("UG", displayName = "Uganda", Franchise.commonwealth),
    "ukraine" -> ISOCountry("UA", displayName = "Ukraine"),
    "united arab emirates" -> ISOCountry("AE", displayName = "United Arab Emirates"),
    "united kingdom" -> ISOCountry("GB", displayName = "United Kingdom", Franchise.full, Franchise.european, Franchise.commonwealth),
    "uruguay" -> ISOCountry("UY", displayName = "Uruguay"),
    "united states of america" -> ISOCountry("US", displayName = "United States of America"),
    "uzbekistan" -> ISOCountry("UZ", displayName = "Uzbekistan"),
    "vanuatu" -> ISOCountry("VU", displayName = "Vanuatu", Franchise.commonwealth),
    "venezuela" -> ISOCountry("VE", displayName = "Venezuela"),
    "vietnam" -> ISOCountry("VN", displayName = "Vietnam"),
    "wallis and futuna" -> ISOCountry("WF", displayName = "Wallis and Futuna"),
    "western sahara" -> ISOCountry("EH", displayName = "Western Sahara"),
    "yemen" -> ISOCountry("YE", displayName = "Yemen"),
    "zambia" -> ISOCountry("ZM", displayName = "Zambia", Franchise.commonwealth),
    "zimbabwe" -> ISOCountry("ZW", displayName = "Zimbabwe", Franchise.commonwealth)
  )




  lazy val countriesExceptUK = countryNameToCodes.filterNot {
    case (name, iso) => iso.isoCode == "GB"
  }

  lazy val validNationalitiesList = countryNameToCodes.filterNot {
    case (name, iso) => List("GB", "GG", "IM", "JE").contains(iso.isoCode)
  }
}
